env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
language: python
python:
  - "3.6"
before_install:
  # Download and install geckodriver
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xvf geckodriver.tar.gz
  - rm geckodriver.tar.gz
  - export PATH=$PATH:$(pwd)
  - geckodriver --version
install:
  # Install dependencies
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate --noinput
script:
  - python manage.py test          # command to run tests
